- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Create a directory
      file:
        path: /tmp/ansible_was_here
        state: directory
